from pydantic import BaseModel, field_validator
from datetime import datetime
from typing import Optional

class FundTransferBase(BaseModel):
    from_account: int
    to_account: int
    amount_cents: int
    notes: Optional[str] = None

    @field_validator('amount_cents')
    def amount_must_be_positive(cls, v):
        if v < 0:
            raise ValueError('Amount cannot be negative')
        return v

class FundTransferCreate(FundTransferBase):
    # Only fields needed for creation
    pass

class FundTransfer(FundTransferBase):
    # All fields including those generated by the database
    id: int
    created_at: datetime

    class Config:
        orm_mode = True